CREATE TABLE PRODUCT
(
   ID VARCHAR (50) PRIMARY KEY,
   VERSION INT NOT NULL,
   NAME VARCHAR (50) NOT NULL,
   STATE VARCHAR (50) NOT NULL
);

CREATE TABLE PRODUCTION_ORDER
(
   ID VARCHAR (50) PRIMARY KEY,
   VERSION INT NOT NULL,
   NAME VARCHAR (50) NOT NULL,
   STATE VARCHAR (20) NOT NULL,
   PRODUCT VARCHAR (50) NOT NULL,
   QUANTITY_TO_PRODUCE INT NOT NULL,
   EXPECTED_COMPLETION_DATE DATE,
   EFFECTIVE_COMPLETION_DATE DATE
);

CREATE TABLE PRODUCT_INVENTORY
(
   PRODUCT_ID VARCHAR (50) PRIMARY KEY,
   VERSION INT NOT NULL,
   PRODUCT_NAME VARCHAR (50) NOT NULL,
   CURRENT_QUANTITY INT NOT NULL,
   NOTIFICATION_THRESHOLD INT NOT NULL,
   LAST_CORRECTED TIMESTAMP,
   LAST_REPLENISHED TIMESTAMP,
   LAST_CONSUMED TIMESTAMP
);

-- from Spring Modulith
CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION
(
   ID UUID NOT NULL,
   COMPLETION_DATE TIMESTAMP (9) WITH TIME ZONE,
   EVENT_TYPE VARCHAR (512) NOT NULL,
   LISTENER_ID VARCHAR (512) NOT NULL,
   PUBLICATION_DATE TIMESTAMP (9) WITH TIME ZONE NOT NULL,
   SERIALIZED_EVENT VARCHAR (4000) NOT NULL,
   PRIMARY KEY (ID)
)