CREATE TABLE PRODUCT (
        ID VARCHAR(50) PRIMARY KEY,
        VERSION INT NOT NULL,
        NAME VARCHAR(50) NOT NULL,
        STATE VARCHAR(50) NOT NULL);

CREATE TABLE PRODUCTION_ORDER (
        ID VARCHAR(50) PRIMARY KEY,
        VERSION INT NOT NULL,
        NAME VARCHAR(50) NOT NULL,
        STATE VARCHAR(20) NOT NULL,
        PRODUCT VARCHAR(50) NOT NULL,
        QUANTITY_TO_PRODUCE INT NOT NULL,
        EXPECTED_COMPLETION_DATE DATE,
        EFFECTIVE_COMPLETION_DATE DATE);

CREATE TABLE PRODUCT_INVENTORY (
        PRODUCT_ID VARCHAR(50) PRIMARY KEY,
        VERSION INT NOT NULL,
        PRODUCT_NAME VARCHAR(50) NOT NULL,
        CURRENT_QUANTITY INT NOT NULL,
        NOTIFICATION_THRESHOLD INT NOT NULL,
        LAST_CORRECTED TIMESTAMP,
        LAST_REPLENISHED TIMESTAMP,
        LAST_CONSUMED TIMESTAMP);